[supervisord]
nodaemon=true
logfile=/tmp/qodo-supervisord.log
pidfile=/tmp/qodo-supervisord.pid

[program:api]
command=go run .
directory=%(here)s/api
environment=GOOGLE_APPLICATION_CREDENTIALS="%(here)s/service-account.json",PORT="4090",GOOGLE_CLOUD_PROJECT="qodo-demo"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:frontend]
command=bunx vite --host --port 4091
directory=%(here)s/frontend
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
